---
title: "Probabilidade e conceitos"
subtitle: "Ciência de Dados Aplicada ao Direito 2"
format:
  insper-revealjs:
    footer: |
      [Ciência de Dados Aplicada ao Direito 2](https://jtrecenti.github.io/202461-cdad2/)
    embed-resources: true
date-format: long
lang: pt

---

## Feedback prova

Preenchimento opcional

{{< qrcode https://forms.gle/rRxCGYtRee1K5C1h7 qr1 height=500 width=500 >}}

## Questão 11

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
  'alternativa': ['A', 'B', 'C', 'D', 'E'],
  'quantidade': [8, 28, 3, 0, 1]
})

sns.barplot(df, x = 'alternativa', y = 'quantidade')
```

## Questão 11 (sem a correta)

```{python}
sns.barplot(df[df.alternativa != 'B'], x = 'alternativa', y = 'quantidade')
```

## Questão 11 (enunciado)

Nosso objetivo é calcular (...)

A - `.agg(count = ('decisao', 'count'))`

B - `.query('polo_mp == "Passivo"')`

C - `.groupby('decisao')`

D - `.reset_index()`

E - `.sort_values('prop', ascending=False)`

F - `.assign(prop = lambda x: x['count'] / x['count'].sum() * 100)`

Coloque essas operações em ordem (...)

a. A,B,C,D,E,F

## Definições

Queremos estudar o tempo dos processos até a sentença no TJSP em 2023.

- Vamos estimar o **tempo médio**.

- Coletamos **100 processos** de forma aleatória no banco de sentenças.

- Utilizamos a **média amostral**, que é a **soma dos valores** dividido pelo total de valores.

- A **soma dos tempos** dos processos é 10.000 dias.

- A **média dos tempos** dos processos coletados é 100 dias.

- O **desvio padrão dos tempos** dos processos é 30 dias.

## Interpretação da probabilidade

{{< qrcode https://forms.gle/1GwVZsjjYcGHxdkf6 qr2 height=500 width=500 >}}